package com.eternax.recon.exception;

/**
 * Stable, documented error codes. The prefix identifies the module that raises the code so an
 * operator can tell where a failure originated from the code alone.
 */
public enum ErrorCode {
    DOM_1001_INVALID_STATE,
    DOM_1002_CURRENCY_MISMATCH,
    DOM_1003_OVER_ALLOCATION,
    DOM_1004_ILLEGAL_TRANSITION,
    ING_2001_SCHEMA_VALIDATION_FAILED,
    ING_2002_DUPLICATE_RECORD,
    ING_2003_SOURCE_UNAVAILABLE,
    ING_2004_CONTROL_TOTAL_MISMATCH,
    NRM_3001_MAPPING_NOT_FOUND,
    NRM_3002_TRANSFORMATION_FAILED,
    MCH_4001_MATCH_EVALUATION_FAILED,
    MCH_4002_RULE_NOT_FOUND,
    MCH_4003_RULE_INVALID,
    EXC_5001_CASE_NOT_FOUND,
    EXC_5002_ILLEGAL_CASE_TRANSITION,
    EXC_5003_TAT_DEADLINE_COMPUTATION_FAILED,
    ADJ_6001_APPROVAL_REQUIRED,
    ADJ_6002_SEPARATION_OF_DUTIES_VIOLATION,
    ADJ_6003_POSTING_FAILED,
    ADJ_6004_DUPLICATE_POSTING_ATTEMPT,
    ORC_6501_RUN_ALREADY_IN_PROGRESS,
    ORC_6502_DEFINITION_LIFECYCLE_VIOLATION,
    PER_7001_OPTIMISTIC_LOCK_CONFLICT,
    PER_7002_ENTITY_NOT_FOUND,
    REQ_7501_MISSING_CONTEXT,
    REQ_7502_IDEMPOTENCY_KEY_REUSED,
    INF_8001_DOWNSTREAM_TIMEOUT,
    INF_8002_DOWNSTREAM_UNAVAILABLE,
    INF_8003_CONFIGURATION_INVALID,
    INF_8000_UNEXPECTED
}
